services:
    accounts:
      image: "rykoond3/accounts:s4"
      container_name: accounts-ms
      ports:
        - "8080:8080"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - finacle

    loans:
      image: "rykoond3/loans:s4"
      container_name: loans-ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - finacle
    cards:
      image: "rykoond3/cards:s4"
      container_name: cards-ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - finacle
networks:
  finacle:
    driver: "bridge"