spring:
  config:
    activate:
      on-profile: "qa"



build:
  version: "2.0"

accounts:
  message: "Welcome to Finaccle accounts related to QA APIs"
  contactDetails:
    name: "John Doe (QA Lead)"
    email: "0bYdX@example.com"
  onCallSupport:
    -(555) 555-5555
    -(555) 555-5556